sudo: required
language: ruby
rvm:
 - 2.3
 - jruby
 gemfile:
    - gemfiles/rails2.gemfile
  
services:
    - docker
    - bundle install --deployment
    - gem update --system

before_install:
   
    - docker build  -t docker-react -f Dockerfile.dev .
   

script:
    - docker run docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-env" 
    backet_name: "elasticbeanstalk-ap-south-1-385452017960"
    backet_path: "docker-react"
    on: 
        branch: master  
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"