sudo: required
language: ruby
rvm :
    - 2.3.3
before_install:
  - gem update --system
  - gem install bundler

#services:
#    - docker
    
#install:
     - bundle install

#before_install:
   
    - docker build  -t docker-react -f Dockerfile.dev .
   

#script:
    - docker run docker-react npm run test -- --coverage