sudo: required
language: ruby
rvm:
 - 2.2
 - jruby

services:
    - docker
    - gem update --system

before_install:
   
    - docker build  -t docker-react -f Dockerfile.dev 
script:
    - docker run docker-react npm run test -- --coverage